language: php
php:
  - 5.3
  - 5.4
before_script:
  - sudo pecl uninstall xdebug
  - curl -s https://getcomposer.org/installer | php -- --quiet 
  - php composer.phar install
script: phpunit -c app/
notifications:
  email:
      - stepan.tanasiychuk@gmail.com
