language: php

sudo: false

php:
  - 5.4

cache:
    directories:
        - $HOME/.composer/cache/files

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer install --dev --prefer-dist --no-interaction
    - ./bin/console doctrine:database:create -e=test -n --no-debug
    - ./bin/console doctrine:schema:create -e=test -n --no-debug
    - ./bin/console assets:install -e=test -n --no-debug
    - ./bin/console cache:warmup -e=test -n --no-debug

script:
    - ./bin/phpunit -c app/

notifications:
    email:
        - stepan.tanasiychuk@gmail.com
