language: php
php:
  - 5.3
  - 5.4
before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install
script: phpunit -c app/
notifications:
  email:
      - stepan.tanasiychuk@gmail.com
