imports:
#    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: 098v442z8bx31nbu
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['php', 'twig'] }
#        escaping:       htmlspecialchars
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     localhost
                dbname:   portfolio_development
                user:     root
                password: null

    orm:
        auto_generate_proxy_classes: %kernel.debug%
#        auto_generate_hydrator_classes:   %kernel.debug%
        default_entity_manager: default
        entity_managers:
            default:
                mappings:
                    PortfolioBundle: ~

## Swiftmailer Configuration
#swiftmailer.config:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx

#jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false


#liip_functionaltest: ~
#
#avalanche_imagine:
#    web_root:     %kernel.root_dir%/../web
#    cache_prefix: imagine
#    driver:       gd
#    filters:
#        thumbnail:
#            type:    thumbnail
#            options: { size: [240, 198], mode: outbound }


imports:
    - { resource: "@PortfolioBundle/Resources/config/menu.xml" }
    
knplabs_menu:
    templating: true