imports:
    - { resource: config.yml }

sentry:
    skip_capture:
        - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
    dsn: "%sentry_dsn_host%"

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped_main
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
#        sentry:
#            type:  raven
#
#            level: error
#            client_id: 'sentry.client'
        grouped_main:
            type:    group
            members: [nested]

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

# AsseticBundle
#assetic:
#    filters:
#        cssrewrite: ~
