imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     localhost
                dbname:   portfolio_development
                user:     root
                password: null
                charset:  UTF8

web_profiler:
    toolbar: true
    intercept_redirects: true

zend:
    logger:
        priority: debug
        path:     %kernel.logs_dir%/%kernel.environment%.log

assetic:
    use_controller: true