imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

# FunctionalTestBundle
liip_functional_test:
    authentication:
        username: admin
        password: qwerty

swiftmailer:
    disable_delivery: true
