imports:
    - { resource: config_dev.yml }

framework:
    error_handler: false
    test: ~

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     localhost
                dbname:   portfolio_development
                user:     root
                password: null
                charset:  UTF8

web_profiler:
    toolbar: false
    intercept_redirects: false

zend:
    logger:
        priority: debug
