imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
        
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     localhost
                dbname:   stfalcon_com_testing
                user:     root
                password: null
                charset:  UTF8

web_profiler:
    toolbar: false
    intercept_redirects: false

# FunctionalTestBundle
liip_functional_test:
    authentication:
        username: admin
        password: qwerty

swiftmailer:
    disable_delivery: true