imports:
    - { resource: config_dev.yml }

doctrine.dbal:
    driver:   pdo_mysql
    dbname:   portfolio_development
#    dbname:   portfolio_testing
    user:     root
    password: null
    logging:  %kernel.debug%

app.config:
    error_handler: false
    test: ~

webprofiler.config:
    toolbar: false
    intercept_redirects: false

zend.config:
    logger:
        priority: debug
