imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     "%kernel.cache_dir%/test.db"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# FunctionalTestBundle
liip_functional_test:
    cache_sqlite_db: true
