imports:
    - { resource: config_dev.yml }

framework:
    error_handler: false
    test: ~

doctrine:
    dbal:
      driver:   pdo_mysql
      dbname:   portfolio_testing
      user:     root
      password: null
      logging:  %kernel.debug%

web_profiler:
    toolbar: false
    intercept_redirects: false

zend:
    logger:
        priority: debug
