framework:
    secret: 098v442z8bx31nbu
    csrf_protection:
        enabled: true
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    session:
        auto_start:     true
        default_locale: ru
        lifetime:       3600
    templating:
        engines: ['twig']
    translator:
        fallback: ru
    validation:
        enabled: true
        annotations: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     localhost
        dbname:   stfalcon_com_development
        user:     root
        password: null
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
        entity_managers:
            default:
                mappings:
                    PortfolioBundle: ~


# DoctrineMigrationsBundle
doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations


# DoctrineMigrationsBundle
doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations


# DoctrineExtensionsBundle
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            loggable: false
            sluggable: true
            timestampable: true
            translatable: false
            tree: false
            

# SecurityBundle
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        main:
            users:
                admin: { password: "qwerty", roles: ROLE_ADMIN }
    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false
        wdt:
            pattern:  ^/_wdt
            security: false
        backend:
            pattern: ^/admin/
            http-basic: true
            logout:     true
    access_control:
        - { path: ^/admin/.*, role: ROLE_ADMIN }


# MenuBundle enable template helpers
knplabs_menu:
    templating: true
    twig: true
# MenuBundle settings
imports:
    - { resource: "@DefaultBundle/Resources/config/menu/menu.xml" }
    - { resource: "@DefaultBundle/Resources/config/menu/breadcrumbs.xml" }

knplabs_paginator:
    templating: ~ # enables view helper and twig

# ZendCacheBundle
zend_cache:
    templates:
        slow_cache:
            frontend:
                name: Core
                options:
                    lifetime: 7200
                    automatic_serialization: true
            backend:
                name: File
                options:
                    cache_dir: %kernel.root_dir%/cache/%kernel.environment%


sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: false }
    view:    { annotations: true, manager_null_arguments: false }
    cache:   { annotations: true }

stfalcon_tinymce: ~