framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['php', 'twig'] }
#        escaping:       htmlspecialchars
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

## Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        dbname:   portfolio_development
        user:     root
        password: null
        logging:  %kernel.debug%
    orm:
        default_entity_manager:           default
        cache_driver:                     apc
        auto_generate_proxy_classes:      %kernel.debug%
    #    auto_generate_hydrator_classes:   %kernel.debug%
        mappings:
            PortfolioBundle: ~

## Swiftmailer Configuration
#swiftmailer.config:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx

#liip_functionaltest: ~
#
#avalanche_imagine:
#    web_root:     %kernel.root_dir%/../web
#    cache_prefix: imagine
#    driver:       gd
#    filters:
#        thumbnail:
#            type:    thumbnail
#            options: { size: [240, 198], mode: outbound }

security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha1
    providers:
        main:
            users:
                foo: { password: 0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33, roles: ROLE_ADMIN }
    firewalls:
        backend:
            pattern: /admin/.*
            http-basic: true
            logout:     true
        public:
            pattern:  /.*
            http-basic: true
    access_control:
        - { path: /admin/.*, role: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
imports:
    - { resource: @PortfolioBundle/Resources/config/menu.xml }
    
knplabs_menu:
    templating: true