imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

doctrine:
    dbal:
        driver:   pdo_mysql
        dbname:   portfolio_development
        user:     root
        password: null
        logging:  %kernel.debug%

web_profiler:
    toolbar: true
    intercept_redirects: true

zend:
    logger:
        priority: debug
        path:     %kernel.logs_dir%/%kernel.environment%.log