app.config:
    charset:       UTF-8
    error_handler: null
    csrf_secret:   xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:
        escaping:       htmlspecialchars
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig.config:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

## Doctrine Configuration
doctrine.dbal:
    driver:   pdo_mysql
    dbname:   symfony2
    user:     root
    password: null
doctrine.orm:
    default_entity_manager:           default
    cache_driver:                     apc
    auto_generate_proxy_classes:      %kernel.debug%
#    auto_generate_hydrator_classes:   %kernel.debug%
    mappings:
        PortfolioBundle: ~

#services:
#    templating.helper.stylesheets:
#        class: Symfony\Bundle\CompatAssetsBundle\Templating\Helper\StylesheetsHelper
#        tags:
#            - { name: templating.helper, alias: stylesheets }
#
## Swiftmailer Configuration
#swiftmailer.config:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx
