_default:
    resource: "@ApplicationDefaultBundle/Controller/DefaultController.php"
    type:     annotation

_portfolio:
    resource: "@StfalconPortfolioBundle/Resources/config/routing.yml"

_blog2:
    resource: "@StfalconBlogBundle/Controller/PostController.php"
    type:     annotation
_blog3:
    resource: "@StfalconBlogBundle/Controller/TagController.php"
    type:     annotation
_blog:
    resource: "@StfalconBlogBundle/Controller/CommentController.php"
    type:     annotation