homepage:
    pattern:  /
    defaults: { _controller: Portfolio:Default:index }

portfolio:
    resource: @Portfolio/Resources/config/routing.yml

# ESI
#_internal:
#    resource: @Framework/Resources/config/routing/internal.xml
#    prefix:   /_internal

#_imagine:
#    resource: .
#    type:     imagine