#homepage:
#    pattern:  /
#    defaults: { _controller: DefaultBundle:Default:index }

homepage:
    pattern:  /{_locale}
    defaults: { _controller: DefaultBundle:Default:index, locale: ru }
    requirements:
        _locale: en|ru

defaultBundle:
    resource: "@DefaultBundle/Resources/config/routing.yml"

portfolioBundle:
    resource: "@PortfolioBundle/Resources/config/routing.yml"