_default:
    resource: "@DefaultBundle/Controller/DefaultController.php"
    type:     annotation

_portfolio:
    resource: "@StfalconPortfolioBundle/Resources/config/routing.yml"

_blog:
    resource: "@StfalconBlogBundle/Resources/config/routing.yml"