_application_default:
    resource: "@ApplicationDefaultBundle/Resources/config/routing.yml"

_stfalcon_portfolio:
    resource: "@StfalconPortfolioBundle/Resources/config/routing.yml"

_stfalcon_blog:
    resource: "@StfalconBlogBundle/Resources/config/routing.yml"

admin:
    resource: "@ApplicationDefaultBundle/Resources/config/custom_sonata_admin.xml"
    defaults:
        _locale: ru
    options:
        i18n: false

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    defaults:
        _locale: ru
    options:
        i18n: false

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    options:
        i18n: false

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    options:
        i18n: false

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

sonata_user:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"
    prefix: /admin
    defaults:
        _locale: ru
    options:
        i18n: false

_imagine:
    resource: .
    type:     imagine

gallery:
    resource: "@SonataMediaBundle/Resources/config/routing/gallery.xml"
    prefix: /media/gallery
    options:
        i18n: false

media:
    resource: "@SonataMediaBundle/Resources/config/routing/media.xml"
    prefix: /media
    options:
        i18n: false

team_route:
    resource: "@ApplicationUserBundle/Controller"
    type: annotation

sonata_admin_price_load:
    path:  /admin/price/load
    defaults: { _controller: ApplicationDefaultBundle:PriceAdmin:load }
    options:
        i18n: false

send_order:
    path:  /order
    defaults: { _controller: ApplicationDefaultBundle:Default:sendOrderByPrice }
    options:
        i18n: false