homepage:
    pattern:  /
    defaults: { _controller: DefaultBundle:Default:index }

defaultBundle:
    resource: "@DefaultBundle/Resources/config/routing.yml"

portfolioBundle:
    resource: "@PortfolioBundle/Resources/config/routing.yml"