homepage:
    pattern:  /
    defaults: { _controller: PortfolioBundle:Default:index }

portfolio:
    resource: @PortfolioBundle/Resources/config/routing.yml

_imagine:
    resource: .
    type:     imagine