# SecurityBundle
security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: %admin_password%, roles: ROLE_ADMIN }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false
        wdt:
            pattern:  ^/_wdt
            security: false
        backend:
            pattern: ^/admin/
            http-basic: true
            logout:     true
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/admin/.*, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN