security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha1

    providers:
        main:
            users:
                foo: { password: 0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33, roles: ROLE_ADMIN }
                
    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        backend:
            pattern: ^/admin/
            http-basic: true
            logout:     true

        public:
            pattern:  ^/
            http-basic: true

    access_control:
        - { path: /admin/.*, role: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }