# SecurityBundle
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        main:
            users:
                admin: { password: "qwerty", roles: ROLE_ADMIN }
    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false
        wdt:
            pattern:  ^/_wdt
            security: false
        backend:
            pattern: ^/admin/
            http-basic: true
            logout:     true
    access_control:
        - { path: ^/admin/.*, role: ROLE_ADMIN }