# DefaultBundle:Default

homepage:
    pattern:  /
    defaults: { _controller: DefaultBundle:Default:index }

portfolioDefaultContacts:
    pattern:  /contacts
    defaults: { _controller: DefaultBundle:Default:contacts }
