_portfolio_redirect:
    resource: "@StfalconPortfolioBundle/Controller/RedirectController.php"
    type:     annotation

_portfolio_project:
    resource: "@StfalconPortfolioBundle/Controller/ProjectController.php"
    type:     annotation

_portfolio_category:
    resource: "@StfalconPortfolioBundle/Controller/CategoryController.php"
    type:     annotation