# PortfolioBundle:Project

portfolioProjectIndex:
    pattern:  /portfolio/projects
    defaults: { _controller: PortfolioBundle:Project:index }

portfolioProjectCreate:
    pattern:  /portfolio/project/create
    defaults: { _controller: PortfolioBundle:Project:create }

portfolioProjectEdit:
    pattern:  /portfolio/project/edit/{id}
    defaults: { _controller: PortfolioBundle:Project:edit }

portfolioProjectView:
    pattern:  /portfolio/project/{id}
    defaults: { _controller: PortfolioBundle:Project:view }

portfolioProjectDelete:
    pattern:  /portfolio/project/delete/{id}
    defaults: { _controller: PortfolioBundle:Project:delete }


# PortfolioBundle:Category

portfolioCategoryIndex:
    pattern:  /portfolio/categories
    defaults: { _controller: PortfolioBundle:Category:index }

portfolioCategoryCreate:
    pattern:  /portfolio/category/create
    defaults: { _controller: PortfolioBundle:Category:create }

portfolioCategoryEdit:
    pattern:  /portfolio/category/edit/{id}
    defaults: { _controller: PortfolioBundle:Category:edit }

portfolioCategoryView:
    pattern:  /portfolio/category/{id}
    defaults: { _controller: PortfolioBundle:Category:view }

portfolioCategoryDelete:
    pattern:  /portfolio/category/delete/{id}
    defaults: { _controller: PortfolioBundle:Category:delete }