# PortfolioBundle:Default

portfolioDefaultContacts:
    pattern:  /contacts
    defaults: { _controller: PortfolioBundle:Default:contacts }


# PortfolioBundle:Project

portfolioProjectIndex:
    pattern:  /admin/portfolio/projects
    defaults: { _controller: PortfolioBundle:Project:index }

portfolioProjectCreate:
    pattern:  /admin/portfolio/project/create
    defaults: { _controller: PortfolioBundle:Project:create }

portfolioProjectEdit:
    pattern:  /admin/portfolio/project/edit/{id}
    defaults: { _controller: PortfolioBundle:Project:edit }

#portfolioProjectView:
#    pattern:  /portfolio/project/{id}
#    defaults: { _controller: PortfolioBundle:Project:view }

portfolioCategoryProjectView:
    pattern:  /portfolio/{categorySlug}/{projectSlug}
    defaults: { _controller: PortfolioBundle:Project:view }

portfolioProjectDelete:
    pattern:  /admin/portfolio/project/delete/{id}
    defaults: { _controller: PortfolioBundle:Project:delete }


# PortfolioBundle:Category

portfolioCategoryIndex:
    pattern:  /admin/portfolio/categories
    defaults: { _controller: PortfolioBundle:Category:index }

portfolioCategoryCreate:
    pattern:  /admin/portfolio/category/create
    defaults: { _controller: PortfolioBundle:Category:create }

portfolioCategoryEdit:
    pattern:  /admin/portfolio/category/edit/{id}
    defaults: { _controller: PortfolioBundle:Category:edit }

#portfolioCategoryView:
#    pattern:  /portfolio/category/{id}
#    defaults: { _controller: PortfolioBundle:Category:view }
portfolioCategoryView:
    pattern:  /portfolio/{id}
    defaults: { _controller: PortfolioBundle:Category:view }

portfolioCategoryDelete:
    pattern:  /admin/portfolio/category/delete/{id}
    defaults: { _controller: PortfolioBundle:Category:delete }