# PortfolioBundle:Project

portfolioProjectIndex:
    pattern:  /admin/portfolio/projects
    defaults: { _controller: PortfolioBundle:Project:index }

portfolioProjectCreate:
    pattern:  /admin/portfolio/project/create
    defaults: { _controller: PortfolioBundle:Project:create }

portfolioProjectEdit:
    pattern:  /admin/portfolio/project/edit/{slug}
    defaults: { _controller: PortfolioBundle:Project:edit }

portfolioProjectView:
    pattern:  /admin/portfolio/project/{id}
    defaults: { _controller: PortfolioBundle:Project:view }
    requirements:
        projectId:     \d+

portfolioCategoryProjectView:
    pattern:  /{_locale}/portfolio/{categorySlug}/{projectSlug}
    defaults: { _controller: PortfolioBundle:Project:view, _locale: ru }
    requirements:
        _locale: en|ru

portfolioProjectDelete:
    pattern:  /admin/portfolio/project/delete/{slug}
    defaults: { _controller: PortfolioBundle:Project:delete }


# PortfolioBundle:Category

portfolioCategoryIndex:
    pattern:  /admin/portfolio/categories
    defaults: { _controller: PortfolioBundle:Category:index }

portfolioCategoryCreate:
    pattern:  /admin/portfolio/category/create
    defaults: { _controller: PortfolioBundle:Category:create }

portfolioCategoryEdit:
    pattern:  /admin/portfolio/category/edit/{slug}
    defaults: { _controller: PortfolioBundle:Category:edit }

portfolioCategoryView:
    pattern:  /{_locale}/portfolio/{slug}
    defaults: { _controller: PortfolioBundle:Category:view, _locale: ru }
    requirements:
        _locale: en|ru

portfolioCategoryDelete:
    pattern:  /admin/portfolio/category/delete/{slug}
    defaults: { _controller: PortfolioBundle:Category:delete }