portfolioProjectIndex:
    pattern:  /portfolio/projects
    defaults: { _controller: PortfolioBundle:Project:index }

portfolioProjectCreate:
    pattern:  /portfolio/project/create
    defaults: { _controller: PortfolioBundle:Project:create }

portfolioProjectEdit:
    pattern:  /portfolio/project/edit/{id}
    defaults: { _controller: PortfolioBundle:Project:edit }

portfolioProjectDelete:
    pattern:  /portfolio/project/delete/{id}
    defaults: { _controller: PortfolioBundle:Project:delete }

portfolioCategoryIndex:
    pattern:  /portfolio/categories
    defaults: { _controller: PortfolioBundle:Category:index }

portfolioCategoryCreate:
    pattern:  /portfolio/category/create
    defaults: { _controller: PortfolioBundle:Category:create }

portfolioCategoryEdit:
    pattern:  /portfolio/category/edit/{id}
    defaults: { _controller: PortfolioBundle:Category:edit }

portfolioCategoryDelete:
    pattern:  /portfolio/category/delete/{id}
    defaults: { _controller: PortfolioBundle:Category:delete }