parameters:
#    stfalcon_re_captcha.example.class: Stfalcon\ReCaptchaBundle\Example

services:
    stfalcon_recaptchabundle.form.type.recaptchaformtype:
        class: Stfalcon\ReCaptchaBundle\Form\Type\ReCaptchaFormType
        arguments:
            - @request
            - %stfalcon.recaptcha.site_key%
            - %stfalcon.recaptcha.secret%
        scope: request
        tags:
            - { name: form.type, alias: recaptcha }

    stfalcon_re_captcha.validator_constraints.valid_captcha_validator:
        class: Stfalcon\ReCaptchaBundle\Validator\Constraints\ValidCaptchaValidator
        arguments: [ @request, @buzz, %stfalcon.recaptcha.site_key%, %stfalcon.recaptcha.secret% ]
        scope: request
        tags:
            - { name: validator.constraint_validator, alias: valid_captcha }
